services:
  rasa:
    image: rasa/rasa:3.6.20-full
    volumes:
      - .:/app
    ports:
      - 5005:5005
    networks:
      - my-project
    command: run --enable-api --cors "*" #--connector socketio

  action-server:
    build:
      context: .
      dockerfile: actions/Dockerfile
    volumes:
      - ./actions:/app/actions
      - ./vector_store:/app/vector_store
    ports:
      - 5055:5055
    networks:
      - my-project
    environment:
      DB_TYPE: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "chatbotdb"
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"  # Load API key from .env
      CURRENT_CLASS: "${CURRENT_CLASS}"  # Load class from .env

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "chatbotdb"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-project

  flask-server:
    build:
      context: .
      dockerfile: flask_backend/Dockerfile
    volumes:
      - ./flask_backend:/app/flask_backend
      - ./shared_models:/app/shared_models
    ports:
      - 8080:8080
    networks:
      - my-project
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "chatbotdb"

  streamlit-app:
    build:
      context: .
      dockerfile: streamlit_frontend/Dockerfile
    volumes:
      - ./streamlit_frontend:/app/streamlit_frontend
      - ./shared_models:/app/shared_models
    ports:
      - "8501:8501"
    networks:
      - my-project
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "chatbotdb"
      CURRENT_CLASS: "${CURRENT_CLASS}"


networks:
  my-project:

volumes:
  postgres_data:
